const ChatMessage = require('../schemas/chat-message');
const User = require('../schemas/user');
const mongoose = require('mongoose');

// Lấy danh sách bạn bè đã từng chat (Contacts)
exports.getChatContacts = async (req, res) => {
    try {
        const userId = req.user._id || req.user.id;

        // Tìm tất cả tin nhắn gửi đi và nhận đến
        const messages = await ChatMessage.find({
            $or: [{ sender: userId }, { receiver: userId }]
        })
        .sort({ createdAt: -1 })
        .populate('sender', 'username email _id')
        .populate('receiver', 'username email _id');

        // Lọc ra unique users dựa trên các tin nhắn
        const contactsMap = new Map();

        messages.forEach(msg => {
            const contactId = msg.sender._id.toString() === userId.toString() 
                ? msg.receiver._id.toString() 
                : msg.sender._id.toString();

            const contactUser = msg.sender._id.toString() === userId.toString() 
                ? msg.receiver 
                : msg.sender;

            // Nếu người dùng này chưa có trong ds thì thêm vào cùng tin nhắn cuối cùng
            if (!contactsMap.has(contactId)) {
                contactsMap.set(contactId, {
                    user: contactUser,
                    lastMessage: {
                        content: msg.content,
                        isAutoGenerated: msg.isAutoGenerated,
                        createdAt: msg.createdAt,
                        senderId: msg.sender._id
                    }
                });
            }
        });

        // Convert Map thành Array
        const contactsList = Array.from(contactsMap.values());

        res.status(200).json({
            success: true,
            data: contactsList
        });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};

// Lấy lịch sử chat với một user cụ thể
exports.getChatHistory = async (req, res) => {
    try {
        const userId = req.user._id || req.user.id;
        const { withUserId } = req.params;

        // Validate ObjectId
        if (!mongoose.Types.ObjectId.isValid(withUserId)) {
            return res.status(400).json({ success: false, message: 'ID người dùng không hợp lệ' });
        }

        const page = parseInt(req.query.page) || 1;
        const limit = parseInt(req.query.limit) || 50; // Load nhiều hơn mặc định cho chat
        const skip = (page - 1) * limit;

        const targetUserExists = await User.exists({ _id: withUserId });
        if (!targetUserExists) {
            return res.status(404).json({ success: false, message: 'Không tìm thấy người dùng' });
        }

        const [messages, total] = await Promise.all([
            ChatMessage.find({
                $or: [
                    { sender: userId, receiver: withUserId },
                    { sender: withUserId, receiver: userId }
                ]
            })
            .sort({ createdAt: -1 }) // Lấy mới nhất về trước, sau đó ở màn chat client thường reverse lại
            .skip(skip)
            .limit(limit)
            .populate('relatedBuild', 'title _id')
            .populate('sender', 'username')
            .populate('receiver', 'username'),
            
            ChatMessage.countDocuments({
                $or: [
                    { sender: userId, receiver: withUserId },
                    { sender: withUserId, receiver: userId }
                ]
            })
        ]);

        res.status(200).json({
            success: true,
            data: messages,
            pagination: {
                page,
                limit,
                total,
                totalPages: Math.ceil(total / limit)
            }
        });

    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};
