const socketIo = require('socket.io');
const jwt = require('jsonwebtoken');
const User = require('../schemas/user');
const ChatMessage = require('../schemas/chat-message');
const express = require('express');

let io;

// Hàm tạo tên phòng chung dựa trên 2 User ID
const getRoomName = (userId1, userId2) => {
    return [userId1.toString(), userId2.toString()].sort().join('_');
};

const initSocket = (server) => {
    io = socketIo(server, {
        cors: {
            origin: "*", // Cấu hình origin phù hợp với frontend thực tế
            methods: ["GET", "POST"]
        }
    });

    // Middleware xác thực token cho Socket
    io.use(async (socket, next) => {
        try {
            const token = socket.handshake.auth.token || socket.handshake.query.token;
            
            if (!token) {
                return next(new Error('Authentication error: Token missing'));
            }

            const decoded = jwt.verify(token, process.env.JWT_SECRET);
            const user = await User.findById(decoded.id);

            if (!user) {
                return next(new Error('Authentication error: User not found'));
            }

            socket.user = user;
            next();
        } catch (error) {
            next(new Error('Authentication error: Invalid token'));
        }
    });

    io.on('connection', (socket) => {
        console.log(`User connected: ${socket.user.username} (${socket.id})`);

        // Join room chat 1-1
        socket.on('join_chat', ({ targetUserId }) => {
            if (!targetUserId) return;
            
            const roomName = getRoomName(socket.user._id, targetUserId);
            socket.join(roomName);
            console.log(`User ${socket.user.username} joined room: ${roomName}`);
            
            // Có thể emit trở lại để confirm
            socket.emit('joined_chat', { room: roomName, targetUserId });
        });

        // Xử lý gửi tin nhắn
        socket.on('send_message', async (data) => {
            try {
                const { receiverId, content, isAutoGenerated, relatedBuildId } = data;
                const senderId = socket.user._id;

                if (!receiverId || !content) {
                    return socket.emit('error_message', { message: 'Receiver and content are required' });
                }

                // Lưu DB
                const newMessage = await ChatMessage.create({
                    sender: senderId,
                    receiver: receiverId,
                    content,
                    isAutoGenerated: isAutoGenerated || false,
                    relatedBuild: relatedBuildId || null
                });

                // Lấy thông tin populate để frontend dễ hiển thị
                await newMessage.populate('relatedBuild', 'title _id');
                await newMessage.populate('sender', 'username email');
                await newMessage.populate('receiver', 'username email');

                // Lấy room name và phát Broadcast tới phòng
                const roomName = getRoomName(senderId, receiverId);
                
                // Emit tin nhắn cho tất cả người trong phòng (bao gồm cả người gửi để họ cập nhật UI)
                io.to(roomName).emit('receive_message', newMessage);

            } catch (error) {
                console.error("Socket send_message error:", error);
                socket.emit('error_message', { message: 'Failed to send message' });
            }
        });

        // Xử lý trạng thái đang nhập chữ
        socket.on('typing', ({ targetUserId, isTyping }) => {
            if (!targetUserId) return;
            const roomName = getRoomName(socket.user._id, targetUserId);
            
            // Broadcast tới những người TRONG PHÒNG KHÁC người gửi
            socket.to(roomName).emit('user_typing', { 
                userId: socket.user._id, 
                isTyping 
            });
        });

        socket.on('disconnect', () => {
            console.log(`User disconnected: ${socket.user.username}`);
        });
    });

    return io;
};

// Hàm lấy io instance nếu cần dùng ngoài file này
const getIo = () => {
    if (!io) {
        throw new Error("Socket.io is not initialized!");
    }
    return io;
};

module.exports = { initSocket, getIo };
