const mongoose = require('mongoose');

const chatMessageSchema = new mongoose.Schema({
  sender: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'user',
    required: true
  },
  receiver: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'user',
    required: true
  },
  content: {
    type: String,
    required: true,
    trim: true
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  // Liên kết đến SharedBuild nếu có để lấy card cấu hình
  relatedBuild: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'SharedBuild'
  }
}, {
  timestamps: true // Thêm createdAt (thời gian gửi) và updatedAt
});

// Index để tối ưu lookup tin nhắn giữa 2 user
chatMessageSchema.index({ sender: 1, receiver: 1 });
chatMessageSchema.index({ createdAt: -1 });

module.exports = mongoose.model('ChatMessage', chatMessageSchema);
